title: CA Conference Deadlines
description: Countdowns to top CA/HPC/EDA/NoC conference deadlines
author: Abhijit Das

domain: "ca-deadlines.github.io"
baseurl: ""

twitter_hashtag: comparch
github_username: ca-deadlines
github_repo: ca-deadlines.github.io

markdown: kramdown
ga_id:

include: ['_pages']
